In [1]:
import urllib.request, json
import requests
import numpy as np
import pandas as pd
from itertools import chain

In [2]:
df = pd.read_csv('/Users/smritimohta/Desktop/Capstone/Final/Code/data_30sec.csv')
df.head()

Unnamed: 0            timestamp   device beacon_type  major    minor  \
0           0  2021-09-14 14:22:30  device1     ibeacon    1.0      0.0   
1           1  2021-09-14 14:23:00  device1     ibeacon    1.0      0.0   
2           2  2021-09-14 14:23:30  device1     ibeacon    1.0      0.0   
3           3  2021-09-14 14:23:30  device1     ibeacon    0.0  18358.0   
4           4  2021-09-14 14:24:00  device1     ibeacon    1.0      0.0   

                                   uuid eddystoneUidData  rssi  tx_power  ...  \
0  2686f39c-bada-4658-854a-a62e7e5e8b8d              NaN   -94       -47  ...   
1  2686f39c-bada-4658-854a-a62e7e5e8b8d              NaN   -92       -47  ...   
2  2686f39c-bada-4658-854a-a62e7e5e8b8d              NaN   -94       -47  ...   
3  74278bda-b644-4520-8f0c-720eaf059935              NaN   -90       -59  ...   
4  2686f39c-bada-4658-854a-a62e7e5e8b8d              NaN   -87       -47  ...   

   BoroCT2020  CDEligibil                              NTAName  NTA2020  \
0     3003700         NaN  Downtown Brooklyn-DUMBO-Boerum Hill   BK0202   
1     3003700         NaN  Downtown Brooklyn-DUMBO-Boerum Hill   BK0202   
2     3003700         NaN  Downtown Brooklyn-DUMBO-Boerum Hill   BK0202   
3     3003700         NaN  Downtown Brooklyn-DUMBO-Boerum Hill   BK0202   
4     3003700         NaN  Downtown Brooklyn-DUMBO-Boerum Hill   BK0202   

   CDTA2020                                           CDTANAME        GEOID  \
0      BK02  BK02 Downtown Brooklyn-Fort Greene (CD 2 Appro...  36047003700   
1      BK02  BK02 Downtown Brooklyn-Fort Greene (CD 2 Appro...  36047003700   
2      BK02  BK02 Downtown Brooklyn-Fort Greene (CD 2 Appro...  36047003700   
3      BK02  BK02 Downtown Brooklyn-Fort Greene (CD 2 Appro...  36047003700   
4      BK02  BK02 Downtown Brooklyn-Fort Greene (CD 2 Appro...  36047003700   

    Shape__Area  Shape__Length  census_id  
0  1.788976e+06    7273.231512        769  
1  1.788976e+06    7273.231512        769  
2  1.788976e+06    7273.231512        769  
3  1.788976e+06    7273.231512        769  
4  1.788976e+06    7273.231512        769  

[5 rows x 35 columns]

In [3]:
df.shape

(10357, 35)

## Unique UUIDs counts and insights

In [ ]:
# first, lets split the eddystone uuid into namespace and instance values

In [4]:
df['instance_id'] = df['eddystoneUidData'].str.slice(17,31)
df['namespace_id'] = df['eddystoneUidData'].str.slice(51,73)
df

Unnamed: 0            timestamp   device    beacon_type  major  \
0               0  2021-09-14 14:22:30  device1        ibeacon    1.0   
1               1  2021-09-14 14:23:00  device1        ibeacon    1.0   
2               2  2021-09-14 14:23:30  device1        ibeacon    1.0   
3               3  2021-09-14 14:23:30  device1        ibeacon    0.0   
4               4  2021-09-14 14:24:00  device1        ibeacon    1.0   
...           ...                  ...      ...            ...    ...   
10352       10352  2021-10-22 17:36:30  device1  eddystone_url    NaN   
10353       10353  2021-10-22 17:37:00  device1  eddystone_url    NaN   
10354       10354  2021-10-22 17:38:00  device1  eddystone_url    NaN   
10355       10355  2021-10-22 17:38:30  device1  eddystone_url    NaN   
10356       10356  2021-10-22 19:44:30  device1  eddystone_url    NaN   

         minor                                  uuid eddystoneUidData  rssi  \
0          0.0  2686f39c-bada-4658-854a-a62e7e5e8b8d              NaN   -94   
1          0.0  2686f39c-bada-4658-854a-a62e7e5e8b8d              NaN   -92   
2          0.0  2686f39c-bada-4658-854a-a62e7e5e8b8d              NaN   -94   
3      18358.0  74278bda-b644-4520-8f0c-720eaf059935              NaN   -90   
4          0.0  2686f39c-bada-4658-854a-a62e7e5e8b8d              NaN   -87   
...        ...                                   ...              ...   ...   
10352      NaN                                   NaN              NaN   -95   
10353      NaN                                   NaN              NaN   -89   
10354      NaN                                   NaN              NaN   -94   
10355      NaN                                   NaN              NaN   -85   
10356      NaN                                   NaN              NaN   -82   

       tx_power  ...                              NTAName  NTA2020  CDTA2020  \
0           -47  ...  Downtown Brooklyn-DUMBO-Boerum Hill   BK0202      BK02   
1           -47  ...  Downtown Brooklyn-DUMBO-Boerum Hill   BK0202      BK02   
2           -47  ...  Downtown Brooklyn-DUMBO-Boerum Hill   BK0202      BK02   
3           -59  ...  Downtown Brooklyn-DUMBO-Boerum Hill   BK0202      BK02   
4           -47  ...  Downtown Brooklyn-DUMBO-Boerum Hill   BK0202      BK02   
...         ...  ...                                  ...      ...       ...   
10352      -100  ...                 Midtown-Times Square   MN0502      MN05   
10353      -100  ...                 Midtown-Times Square   MN0502      MN05   
10354      -100  ...                 Midtown-Times Square   MN0502      MN05   
10355      -100  ...                 Midtown-Times Square   MN0502      MN05   
10356       -77  ...                 Midtown-Times Square   MN0502      MN05   

                                                CDTANAME        GEOID  \
0      BK02 Downtown Brooklyn-Fort Greene (CD 2 Appro...  36047003700   
1      BK02 Downtown Brooklyn-Fort Greene (CD 2 Appro...  36047003700   
2      BK02 Downtown Brooklyn-Fort Greene (CD 2 Appro...  36047003700   
3      BK02 Downtown Brooklyn-Fort Greene (CD 2 Appro...  36047003700   
4      BK02 Downtown Brooklyn-Fort Greene (CD 2 Appro...  36047003700   
...                                                  ...          ...   
10352  MN05 Midtown-Flatiron-Union Square (CD 5 Appro...  36061011300   
10353  MN05 Midtown-Flatiron-Union Square (CD 5 Appro...  36061011300   
10354  MN05 Midtown-Flatiron-Union Square (CD 5 Appro...  36061011300   
10355  MN05 Midtown-Flatiron-Union Square (CD 5 Appro...  36061011300   
10356  MN05 Midtown-Flatiron-Union Square (CD 5 Appro...  36061011300   

        Shape__Area Shape__Length  census_id  instance_id  namespace_id  
0      1.788976e+06   7273.231512        769          NaN           NaN  
1      1.788976e+06   7273.231512        769          NaN           NaN  
2      1.788976e+06   7273.231512        769          NaN           NaN  
3      1.788976e+06   7273.231512        769   

In [25]:
pd.set_option('display.max_columns', None)
df.head()

Unnamed: 0            timestamp   device beacon_type  major    minor  \
0           0  2021-09-14 14:22:30  device1     ibeacon    1.0      0.0   
1           1  2021-09-14 14:23:00  device1     ibeacon    1.0      0.0   
2           2  2021-09-14 14:23:30  device1     ibeacon    1.0      0.0   
3           3  2021-09-14 14:23:30  device1     ibeacon    0.0  18358.0   
4           4  2021-09-14 14:24:00  device1     ibeacon    1.0      0.0   

                                   uuid eddystoneUidData  rssi  tx_power  \
0  2686f39c-bada-4658-854a-a62e7e5e8b8d              NaN   -94       -47   
1  2686f39c-bada-4658-854a-a62e7e5e8b8d              NaN   -92       -47   
2  2686f39c-bada-4658-854a-a62e7e5e8b8d              NaN   -94       -47   
3  74278bda-b644-4520-8f0c-720eaf059935              NaN   -90       -59   
4  2686f39c-bada-4658-854a-a62e7e5e8b8d              NaN   -87       -47   

    distance   latitude  longitude  speed(m/s)  manufacturer      last_seen  \
0  50.990363  40.690918 -73.986798        1.02            76  1628298167545   
1  50.448288  40.690898 -73.986413        1.17            76  1628298168647   
2  50.617148  40.690825 -73.986106        1.12            76  1628298170850   
3   4.484340  40.690803 -73.986018        0.96            76  1628298171947   
4  45.537935  40.690675 -73.985712        1.06            76  1628298171947   

                              coordinates  index_right  level_0  level_1  \
0         POINT (-73.98679796 40.6909178)          769      698        0   
1   POINT (-73.98641318999999 40.6908978)          769      698        0   
2        POINT (-73.98610619 40.69082545)          769      698        0   
3  POINT (-73.98601773999999 40.69080287)          769      698        0   
4  POINT (-73.98571164000001 40.69067456)          769      698        0   

   OBJECTID  CTLabel  BoroCode  BoroName  CT2020  BoroCT2020  CDEligibil  \
0       699     37.0         3  Brooklyn    3700     3003700         NaN   
1       699     37.0         3  Brooklyn    3700     3003700         NaN   
2       699     37.0         3  Brooklyn    3700     3003700         NaN   
3       699     37.0         3  Brooklyn    3700     3003700         NaN   
4       699     37.0         3  Brooklyn    3700     3003700         NaN   

                               NTAName NTA2020 CDTA2020  \
0  Downtown Brooklyn-DUMBO-Boerum Hill  BK0202     BK02   
1  Downtown Brooklyn-DUMBO-Boerum Hill  BK0202     BK02   
2  Downtown Brooklyn-DUMBO-Boerum Hill  BK0202     BK02   
3  Downtown Brooklyn-DUMBO-Boerum Hill  BK0202     BK02   
4  Downtown Brooklyn-DUMBO-Boerum Hill  BK0202     BK02   

                                            CDTANAME        GEOID  \
0  BK02 Downtown Brooklyn-Fort Greene (CD 2 Appro...  36047003700   
1  BK02 Downtown Brooklyn-Fort Greene (CD 2 Appro...  36047003700   
2  BK02 Downtown Brooklyn-Fort Greene (CD 2 Appro...  36047003700   
3  BK02 Downtown Brooklyn-Fort Greene (CD 2 Appro...  36047003700   
4  BK02 Downtown Brooklyn-Fort Greene (CD 2 Appro...  36047003700   

    Shape__Area  Shape__Length  census_id instance_id namespace_id  
0  1.788976e+06    7273.231512        769         NaN          NaN  
1  1.788976e+06    7273.231512        769         NaN          NaN  
2  1.788976e+06    7273.231512        769         NaN          NaN  
3  1.788976e+06    7273.231512        769         NaN          NaN  
4  1.788976e+06    7273.231512        769         NaN          NaN

In [81]:
df.shape

(10357, 37)

In [17]:
# overall beacon counts by uuids
df['beacon_type'].unique()

array(['ibeacon', 'altbeacon', 'eddystone_uid', 'eddystone_url'],
      dtype=object)

## Beacon counts by Unique UUIDs and their geographies

### iBeacons

In [12]:
df[df['beacon_type']=='ibeacon'][['beacon_type','uuid']].groupby(by=
              ['uuid']).count().sort_values(by=['beacon_type'], ascending=False).rename(columns={'beacon_type':'count'})


count
uuid                                       
5993a94c-7d97-4df7-9abf-e493bfd5d000    969
50765cb7-d9ea-4e21-99a4-fa879613a492    948
74278bda-b644-4520-8f0c-720eaf059935    745
2686f39c-bada-4658-854a-a62e7e5e8b8d    645
8a21c76b-74e3-4341-92be-33fcfdefdd63    451
...                                     ...
010e5daf-960b-43da-b605-89d5f040b217      1
df5558f8-0c2e-46e6-9da9-4c82824ceda1      1
40a480af-a022-4050-95d6-51a700020000      1
e1717541-3116-b5a5-8f5c-458db726c2b7      1
7f94e960-5490-41b2-b762-4ab5fc87384c      1

[203 rows x 1 columns]

In [19]:
# lets see where the top 5 ibeacons are found: 
df[df['uuid']=='5993a94c-7d97-4df7-9abf-e493bfd5d000']['census_id'].unique()

array([ 752,  749,   19,  767,  758,  750,   51,   78, 1092, 1181, 1207,
       1248, 1246,  122,   72,   66,   69,   55,   70,   53,  147])

In [20]:
df[df['uuid']=='50765cb7-d9ea-4e21-99a4-fa879613a492']['census_id'].unique()

array([ 749,   19,   13,   29,  954,  881,  874,  873,  871,  855,  853,
        847,  846,  767,  124,  122,  109,  107,  101,   79,   60,   31,
        758,   51,   32,   66,   77,   76,   74,   78,   23, 1127, 1125,
       1143,  969,  996, 1092,  117,  115,   75,  106,  143,  130,  134,
        135,  133,  148,  145,  120,  131,  146,  149,   61,   34,   55,
         53,  805,  797,  800,  799,  773,  769,  132,  141,  147,  154,
        150])

In [21]:
df[df['uuid']=='74278bda-b644-4520-8f0c-720eaf059935']['census_id'].unique()

array([ 769,   19,   13,   29,   28,  938,  892,  881,  874,  873,  871,
        855,  853,  877,  847,  846,  767,  122,  124,  101,   99,   78,
         83,   79,   65,   60,  758,  752,   51,   32,   66,   77,   76,
         72,   89,   74,   73,  977,  979,   23,  998, 1096, 1981, 1145,
        968,  969,  996,  134,  144,  145,  133,  120,  131,  146,   61,
         34,   55,   53,   87,  749,  748,  775,  747,  778,  797,  805,
        799,  773,  141,  109,  147,  154,  150,  143,  107])

In [23]:
df[df['uuid']=='8a21c76b-74e3-4341-92be-33fcfdefdd63']['census_id'].unique()

array([752,  19,  13,  29, 954, 938, 881, 874, 871, 855, 846, 847, 767,
        78,  73,  74, 758,  20,  51,  25,  32,  66,  77,  72,  83, 749,
       769, 958, 977, 979,  53,  34,  23, 969, 108, 130, 124, 135, 145,
       122, 120, 131, 146, 149, 133,  61,  55,  87, 775, 805, 797, 773,
       748, 141, 101, 109, 147, 154, 150, 143, 107])

In [ ]:
df[df['uuid']=='2686f39c-bada-4658-854a-a62e7e5e8b8d']['census_id'].unique()

### Altbeacons

In [13]:
# altbeacons
df[df['beacon_type']=='altbeacon'][['beacon_type','uuid']].groupby(by=
              ['uuid']).count().sort_values(by=['beacon_type'], ascending=False).rename(columns={'beacon_type':'count'})


count
uuid                                       
2f234454-cf6d-4a0f-adf2-f4911ba9ffa6      8
43a2bc29-c111-4a76-8b6f-78aecb142e5a      1

In [24]:
# lets see where the top 2 altbeacons are found: 
df[df['uuid']=='2f234454-cf6d-4a0f-adf2-f4911ba9ffa6']['census_id'].unique()

array([ 28, 846, 847, 767,  51, 135, 120, 150, 147, 109])

In [25]:
df[df['uuid']=='43a2bc29-c111-4a76-8b6f-78aecb142e5a']['census_id'].unique()

array([141])

### Eddystone UID

In [18]:
# eddystone_uid
df[df['beacon_type']=='eddystone_uid'][['beacon_type','namespace_id']].groupby(by=
              ['namespace_id']).count().sort_values(by=['beacon_type'], ascending=False).rename(columns={'beacon_type':'count'})


count
namespace_id                 
0xb2e5fc49d46042b9893c   1697
0xc1cac1c417534ddea065    751
0x2a28c8e5b65f44aa9837    100
0x85ceeb822284d5870c3a     50
0xe1bde705bd3940898e3d     32
0x5713793103decaf22026     10
0x71410849e0b34b5f9819      8
0xc4abe71156a5fa70a23f      7
0x9e9f052935fc2bc872e6      5
0xf7826da6bc5b71e0893e      3
0x670d6c28e1a4bdb78331      1

In [26]:
# lets see where the top 5 eddystone uids are found: 
df[df['namespace_id']=='0xb2e5fc49d46042b9893c']['census_id'].unique()

array([149, 146, 133, 122, 124,  23,  34, 345,  61, 109, 141, 101, 107,
       132])

In [27]:
df[df['namespace_id']=='0xc1cac1c417534ddea065']['census_id'].unique()

array([124, 122, 109, 107, 101,  23,  28, 133, 120, 147, 141])

In [28]:
df[df['namespace_id']=='0x2a28c8e5b65f44aa9837']['census_id'].unique()

array([74, 78])

In [29]:
df[df['namespace_id']=='0x85ceeb822284d5870c3a']['census_id'].unique()

array([130, 109, 141, 147, 101])

In [30]:
df[df['namespace_id']=='0xe1bde705bd3940898e3d']['census_id'].unique()

array([143, 141])

## Company merged UUIDs insights

In [31]:
company = pd.read_csv('/Users/smritimohta/Desktop/Capstone/Final/Code/Beacon_Manufacturers.csv')
company = company[['Company_Names','Example_UUID','Namespace_id']].rename(columns={'Namespace_id':'namespace_id'})
company.head()

Company_Names                          Example_UUID  \
0  BlueCats (Plus Location Systems  61687109-905f-4436-91f8-e602f514c96d   
1              Bluebar (BlueSense)  a0b13730-3a9a-11e3-aa6e-0800200c9a66   
2                         Estimote  b9407f30-f5f8-466e-aff9-25556b57fe6d   
3                             Gelo  11e44f09-4ec4-407e-9203-cf57a50fbce0   
4                         Glimworm  74278bda-b644-4520-8f0c-720eaf059935   

  namespace_id  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN

In [32]:
# processing the data
company['Example_UUID'] = company['Example_UUID'].str.lower()
company['uuid_code'] = company['Example_UUID'].str.slice(0,8)
company['uuid_code'][10] = company['namespace_id'][10]
company.head()

Company_Names                          Example_UUID  \
0  BlueCats (Plus Location Systems  61687109-905f-4436-91f8-e602f514c96d   
1              Bluebar (BlueSense)  a0b13730-3a9a-11e3-aa6e-0800200c9a66   
2                         Estimote  b9407f30-f5f8-466e-aff9-25556b57fe6d   
3                             Gelo  11e44f09-4ec4-407e-9203-cf57a50fbce0   
4                         Glimworm  74278bda-b644-4520-8f0c-720eaf059935   

  namespace_id uuid_code  
0          NaN  61687109  
1          NaN  a0b13730  
2          NaN  b9407f30  
3          NaN  11e44f09  
4          NaN  74278bda

In [33]:
# merging with main dataframe
df_merge = df.merge(company, on='uuid_code', how='left')
df_merge.head()

Unnamed: 0            timestamp   device beacon_type  major    minor  \
0           0  2021-09-14 14:22:30  device1     ibeacon    1.0      0.0   
1           1  2021-09-14 14:23:00  device1     ibeacon    1.0      0.0   
2           2  2021-09-14 14:23:30  device1     ibeacon    1.0      0.0   
3           3  2021-09-14 14:23:30  device1     ibeacon    0.0  18358.0   
4           4  2021-09-14 14:24:00  device1     ibeacon    1.0      0.0   

                                   uuid eddystoneUidData  rssi  tx_power  ...  \
0  2686f39c-bada-4658-854a-a62e7e5e8b8d              NaN   -94       -47  ...   
1  2686f39c-bada-4658-854a-a62e7e5e8b8d              NaN   -92       -47  ...   
2  2686f39c-bada-4658-854a-a62e7e5e8b8d              NaN   -94       -47  ...   
3  74278bda-b644-4520-8f0c-720eaf059935              NaN   -90       -59  ...   
4  2686f39c-bada-4658-854a-a62e7e5e8b8d              NaN   -87       -47  ...   

         GEOID   Shape__Area  Shape__Length  census_id  instance_id  \
0  36047003700  1.788976e+06    7273.231512        769          NaN   
1  36047003700  1.788976e+06    7273.231512        769          NaN   
2  36047003700  1.788976e+06    7273.231512        769          NaN   
3  36047003700  1.788976e+06    7273.231512        769          NaN   
4  36047003700  1.788976e+06    7273.231512        769          NaN   

   namespace_id_x uuid_code  Company_Names  \
0             NaN  2686f39c            NaN   
1             NaN  2686f39c            NaN   
2             NaN  2686f39c            NaN   
3             NaN  74278bda       Glimworm   
4             NaN  2686f39c            NaN   

                           Example_UUID  namespace_id_y  
0                                   NaN             NaN  
1                                   NaN             NaN  
2                                   NaN             NaN  
3  74278bda-b644-4520-8f0c-720eaf059935             NaN  
4                                   NaN             NaN  

[5 rows x 41 columns]

In [46]:
# sorting to count numbers of company matched beacon products : ibeacon & altbeacon protocol - 13 uuids matched 
df_merge[['uuid','beacon_type','Company_Names']].groupby(by=['Company_Names',
                        'uuid',]).count().sort_values(by='beacon_type',ascending=False).reset_index()

Company_Names  \
0                               Glimworm   
1                                   SXSW   
2                        Apple AirLocate   
3   Omni access stellar (Alcatel Lucent)   
4                         Motorola MPact   
5               RadBeacon/Radius Network   
6                            Onyx beacon   
7                                 Skylab   
8           Aruba Bluetooth Beacons (HP)   
9                               Aerohive   
10                               Kontakt   
11                                Skylab   
12                                Skylab   

                                    uuid  beacon_type  
0   74278bda-b644-4520-8f0c-720eaf059935          745  
1   d77657c4-52a7-426f-b9d0-d71e10798c8a          303  
2   e2c56db5-dffb-48d2-b060-d0f5a71096e0          260  
3   504f4c45-5354-4152-0000-000000000000          168  
4   fe913213-b311-4a42-8c16-47faeac938db           29  
5   2f234454-cf6d-4a0f-adf2-f4911ba9ffa6           22  
6   20cae8a0-a9cf-11e3-a5e2-0800200c9a66           20  
7   fda50693-a4e2-4fb1-afcf-c6eb07647825           12  
8   4152554e-f99b-4a3b-86d0-947070693a78           11  
9   4165726f-6869-7665-4e65-74776f726b73           10  
10  f7826da6-4fa2-4e98-8024-bc5b71e0893e            9  
11  fda50693-a4e2-4fb1-3344-ff767760cac6            8  
12  fda50693-a4e2-4fb1-3344-df97a470ee50            1

In [47]:
# sorting to count numbers of company matched beacon products : eddystone protocol - 0 uuids matched 
df_merge[['namespace_id_x','beacon_type','Company_Names']].groupby(by=['Company_Names',
                        'namespace_id_x',]).count().sort_values(by='beacon_type',ascending=False).reset_index()

Empty DataFrame
Columns: [Company_Names, namespace_id_x, beacon_type]
Index: []

## Street addresses insights on company matched uuids

In [55]:
df_revins= pd.read_csv('/Users/smritimohta/Desktop/Capstone/Final/Code/final_merged_data.csv')
df_revins.head()

/Users/smritimohta/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (6,38,64,68,70,71,72,74) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


Unnamed: 0            timestamp   device beacon_type  major    minor  \
0           0  2021-09-14 14:22:30  device1     ibeacon    1.0      0.0   
1           1  2021-09-14 14:23:00  device1     ibeacon    1.0      0.0   
2           2  2021-09-14 14:23:30  device1     ibeacon    1.0      0.0   
3           3  2021-09-14 14:23:30  device1     ibeacon    0.0  18358.0   
4           4  2021-09-14 14:24:00  device1     ibeacon    1.0      0.0   

                                   uuid eddystoneUidData  rssi  tx_power  ...  \
0  2686f39c-bada-4658-854a-a62e7e5e8b8d              NaN   -94       -47  ...   
1  2686f39c-bada-4658-854a-a62e7e5e8b8d              NaN   -92       -47  ...   
2  2686f39c-bada-4658-854a-a62e7e5e8b8d              NaN   -94       -47  ...   
3  74278bda-b644-4520-8f0c-720eaf059935              NaN   -90       -59  ...   
4  2686f39c-bada-4658-854a-a62e7e5e8b8d              NaN   -87       -47  ...   

   tourism  highway  office  craft  quarter  place residential  retail  \
0      NaN      NaN     NaN    NaN      NaN    NaN         NaN     NaN   
1      NaN      NaN     NaN    NaN      NaN    NaN         NaN     NaN   
2      NaN      NaN     NaN    NaN      NaN    NaN         NaN     NaN   
3      NaN      NaN     NaN    NaN      NaN    NaN         NaN     NaN   
4      NaN      NaN     NaN    NaN      NaN    NaN         NaN     NaN   

   man_made  commercial  
0       NaN         NaN  
1       NaN         NaN  
2       NaN         NaN  
3       NaN         NaN  
4       NaN         NaN  

[5 rows x 75 columns]

In [56]:
df_revins.columns

Index(['Unnamed: 0', 'timestamp', 'device', 'beacon_type', 'major', 'minor',
       'uuid', 'eddystoneUidData', 'rssi', 'tx_power', 'distance', 'latitude',
       'longitude', 'speed(m/s)', 'manufacturer', 'last_seen', 'coordinates',
       'index_right', 'level_0', 'level_1', 'OBJECTID', 'CTLabel', 'BoroCode',
       'BoroName', 'CT2020', 'BoroCT2020', 'CDEligibil', 'NTAName', 'NTA2020',
       'CDTA2020', 'CDTANAME', 'GEOID', 'Shape__Area', 'Shape__Length',
       'census_id', 'instance_id', 'namespace_id_x', 'uuid_code',
       'Company_Names', 'geometry', 'place_id', 'licence', 'osm_type',
       'osm_id', 'lat', 'lon', 'display_name', 'boundingbox', 'house_number',
       'road', 'neighbourhood', 'suburb', 'city_district', 'city', 'state',
       'postcode', 'country', 'country_code', 'amenity', 'railway', 'shop',
       'building', 'leisure', 'county', 'historic', 'tourism', 'highway',
       'office', 'craft', 'quarter', 'place', 'residential', 'retail',
       'man_made', 'comm

In [85]:
trial = df_revins[['beacon_type','census_id','display_name','uuid','Company_Names']].groupby(by=['census_id',
                        'display_name','uuid','Company_Names']).count().sort_values(by=['beacon_type'],
                                                                                      ascending=False).reset_index()
trial

census_id                                       display_name  \
0          147  42nd Street–Times Square–Port Authority Bus Te...   
1          141  Herald Square Building, 1350, Broadway, Garmen...   
2          147  42nd Street–Times Square–Port Authority Bus Te...   
3          109  1, West 37th Street, Midtown South, Manhattan ...   
4          109  65, West 37th Street, Midtown South, Manhattan...   
..         ...                                                ...   
959        109  21, West 37th Street, Midtown South, Manhattan...   
960        109  25, West 39th Street, Midtown South, Manhattan...   
961        109  29, West 36th Street, Midtown South, Manhattan...   
962        109  34th Street–Herald Square, PATH - 33rd Street ...   
963       1981  Myrtle-Wyckoff Avenues, Palmetto Street, Ridge...   

                                     uuid  \
0    504f4c45-5354-4152-0000-000000000000   
1    504f4c45-5354-4152-0000-000000000000   
2    74278bda-b644-4520-8f0c-720eaf059935   
3    504f4c45-5354-4152-0000-000000000000   
4    504f4c45-5354-4152-0000-000000000000   
..                                    ...   
959  e2c56db5-dffb-48d2-b060-d0f5a71096e0   
960  d77657c4-52a7-426f-b9d0-d71e10798c8a   
961  74278bda-b644-4520-8f0c-720eaf059935   
962  504f4c45-5354-4152-0000-000000000000   
963  74278bda-b644-4520-8f0c-720eaf059935   

                            Company_Names  beacon_type  
0    Omni access stellar (Alcatel Lucent)           20  
1    Omni access stellar (Alcatel Lucent)           13  
2                                Glimworm           12  
3    Omni access stellar (Alcatel Lucent)           11  
4    Omni access stellar (Alcatel Lucent)           11  
..                                    ...          ...  
959                       Apple AirLocate            1  
960                                  SXSW            1  
961                              Glimworm            1  
962  Omni access stellar (Alcatel Lucent)            1  
963                              Glimworm            1  

[964 rows x 5 columns]

In [86]:
trial[trial['Company_Names']=='Omni access stellar (Alcatel Lucent)']

census_id                                       display_name  \
0          147  42nd Street–Times Square–Port Authority Bus Te...   
1          141  Herald Square Building, 1350, Broadway, Garmen...   
3          109  1, West 37th Street, Midtown South, Manhattan ...   
4          109  65, West 37th Street, Midtown South, Manhattan...   
7          109  The Vogue, 990, 6th Avenue, Midtown South, Man...   
9          109  20, West 38th Street, Midtown South, Manhattan...   
17         141  Citi Bike - Broadway & W 36 St, Broadway, Garm...   
20         141  34th Street–Herald Square, PATH - 33rd Street ...   
21         141  34th Street - Herald Square (B,D,F,M), 6th Ave...   
23         109  420, 5th Avenue, Midtown South, Manhattan Comm...   
51         141  Haier Building, West 36th Street, Garment Dist...   
53         141  1367, Broadway, Garment District, Manhattan Co...   
54         141  1359, Broadway, Garment District, Manhattan Co...   
64         109  1024, 6th Avenue, Midtown South, Manhattan Com...   
65         109  6th Avenue & West 37th Street, 6th Avenue, Mid...   
85         147  120, West 39th Street, Garment District, Manha...   
98         141  Fresh & Co, West 36th Street, Garment District...   
106        109  6th Avenue & West 38th Street, 6th Avenue, Mid...   
108        147  42nd Street–Times Square, Broadway, Garment Di...   
116        109  21617, 6th Avenue, Midtown South, Manhattan Co...   
126        109  1020, 6th Avenue, Midtown South, Manhattan Com...   
148        141  Shake Shack, 1333, Broadway, Garment District,...   
166        109  78, West 36th Street, Midtown South, Manhattan...   
171        109  18, West 38th Street, Midtown South, Manhattan...   
176        109  PrimeXchange, 1000, 6th Avenue, Midtown South,...   
194        141  V&S Gallery, West 37th Street, Garment Distric...   
230        147  1400 Broadway, 1400, Broadway, Garment Distric...   
248        141  550, 8th Avenue, Garment District, Manhattan C...   
253        141  121, 6th Avenue, Garment District, Manhattan C...   
312        150  575, 8th Avenue, Garment District, Manhattan C...   
343        150  580, 8th Avenue, Garment District, Manhattan C...   
359        147  Tees Gifts, Broadway, Garment District, Manhat...   
830        141  Cava, 1385, Broadway, Garment District, Manhat...   
831        141  Dunkin' Donuts, West 37th Street, Garment Dist...   
834        141  Ebad Fabrics, 550, 8th Avenue, Garment Distric...   
838        141  NICE Actimize, Broadway, Garment District, Man...   
839        141  NS4036, 6th Avenue, Garment District, Manhatta...   
845        141  1375, Broadway, Garment District, Manhattan Co...   
854        141  1013, 6th Avenue, Garment District, Manhattan ...   
857        141  140, West 38th Street, Garment District, Manha...   
882        101  34th Street–Herald Square, PATH - 33rd Street ...   
942        109  1028, 6th Avenue, Midtown South, Manhattan Com...   
948        109  1006, 6th Avenue, Midtown South, Manhattan Com...   
950        109  1026, 6th Avenue, Midtown South, Manhattan Com...   
962        109  34th Street–Herald Square, PATH - 33rd Street ...   

                                     uuid  \
0    504f4c45-5354-4152-0000-000000000000   
1    504f4c45-5354-4152-0000-000000000000   
3    504f4c45-5354-4152-0000-000000000000   
4    504f4c45-5354-4152-0000-000000000000   
7    504f4c45-5354-4152-0000-000000000000   
9    504f4c45-5354-4152-0000-000000000000   
17   504f4c45-5354-4152-0000-000000000000   
20   504f4c45-5354-4152-0000-000000000000   
21   504f4c45-5354-4152-0000-000000000000   
23   504f4c45-5354-4152-0000-000000000000   
51   504f4c45-5354-4152-0000-000000000000   
53   504f4c45-5354-4152-0000-000000000000   
54   504f4c45-5354-4152-0000-000000000000   
64   504f4c45-5354-4152-0000-000000000000   
65   504f4c45-5354-4152-0000-000000000000   
85   504f4c45-5354-4152-0000-000000000000   
98   504f4c45-5354-4152-0000-000000000000   
106  504f4c45-5354-4

In [79]:
pd.set_option('display.max_columns', None)
df_revins[(df_revins['road']=='West Broadway') & (df_revins['uuid']=='d954b22d-0031-4b02-b91d-f86c1fbd8d22')]

Unnamed: 0            timestamp   device beacon_type   major   minor  \
4506        4506  2021-10-16 19:02:30  device1     ibeacon  1000.0  3223.0   
4507        4507  2021-10-16 19:02:30  device1     ibeacon  1000.0  3222.0   
4508        4508  2021-10-16 19:02:30  device1     ibeacon  1000.0  3272.0   
4517        4517  2021-10-16 19:03:30  device1     ibeacon  1000.0  3194.0   
4518        4518  2021-10-16 19:03:30  device1     ibeacon  1000.0  3313.0   
...          ...                  ...      ...         ...     ...     ...   
4868        4868  2021-10-16 19:14:30  device1     ibeacon  1000.0  3194.0   
4888        4888  2021-10-16 19:15:00  device1     ibeacon  1000.0  3249.0   
4906        4906  2021-10-16 19:15:30  device1     ibeacon  1000.0  3284.0   
4908        4908  2021-10-16 19:16:00  device1     ibeacon  1000.0  3284.0   
4913        4913  2021-10-16 19:16:00  device1     ibeacon  1000.0  3194.0   

                                      uuid eddystoneUidData  rssi  tx_power  \
4506  d954b22d-0031-4b02-b91d-f86c1fbd8d22              NaN   -90       -49   
4507  d954b22d-0031-4b02-b91d-f86c1fbd8d22              NaN   -87       -49   
4508  d954b22d-0031-4b02-b91d-f86c1fbd8d22              NaN   -89       -49   
4517  d954b22d-0031-4b02-b91d-f86c1fbd8d22              NaN   -87       -49   
4518  d954b22d-0031-4b02-b91d-f86c1fbd8d22              NaN   -87       -49   
...                                    ...              ...   ...       ...   
4868  d954b22d-0031-4b02-b91d-f86c1fbd8d22              NaN   -82       -49   
4888  d954b22d-0031-4b02-b91d-f86c1fbd8d22              NaN   -89       -49   
4906  d954b22d-0031-4b02-b91d-f86c1fbd8d22              NaN   -89       -49   
4908  d954b22d-0031-4b02-b91d-f86c1fbd8d22              NaN   -89       -49   
4913  d954b22d-0031-4b02-b91d-f86c1fbd8d22              NaN   -80       -49   

       distance   latitude  longitude  speed(m/s)  manufacturer  \
4506  29.303959  40.716130 -74.008933        1.15            76   
4507  23.269880  40.716130 -74.008933        1.15            76   
4508  27.156289  40.716137 -74.008921        1.12            76   
4517  20.144908  40.716227 -74.008605        0.85            76   
4518  23.269880  40.716227 -74.008605        0.85            76   
...         ...        ...        ...         ...           ...   
4868  14.874892  40.720402 -74.005379        1.29            76   
4888  34.047691  40.720525 -74.005129        1.08            76   
4906  27.156289  40.720967 -74.004948        1.11            76   
4908  27.156289  40.721017 -74.004881        1.03            76   
4913  18.110292  40.721053 -74.004830        1.23            76   

          last_seen                             coordinates  index_right  \
4506  1634424401316        POINT (-74.00893322 40.71612971)           55   
4507  1634424401350        POINT (-74.00893322 40.71612971)           55   
4508  1634424402165        POINT (-74.00892095 40.71613742)           55   
4517  1634424402178         POINT (-74.0086046 40.71622698)           55   
4518  1634424402164         POINT (-74.0086046 40.71622698)           55   
...             ...                                     ...          ...   
4868  1634424511600        POINT (-74.00537926 40.72040178)           55   
4888  1634424513891        POINT (-74.00512866 40.72052473)           55   
4906  1634424517273        POINT (-74.00494771 40.72096671)           55   
4908  1634424517273  POINT (-74.00488147999999 40.72101687)           55   
4913  1634424520225        POINT (-74.00483005 40.72105253)           55   

      level_0  level_1  OBJECTID  CTLabel  BoroCode   BoroName  CT2020  \
4506       34        0        35     33.0         1  Manhattan    3300   
4507       34        0        35     33.0         1  Manhattan    3300   
4508       34        0        35     33.0         1  Manhattan    3300   
4517       34        0        35     33.0         1  Manhattan    3300   
4518       34        0        35